model_dir: object_models
render_overlay_default: true
output_units: deg
icp_threshold: 0.02
max_icp_iterations: 50
robot_pose:
  translation:
  - 0.0
  - 0.0
  - 0.0
  rotation_deg:
  - 0.0
  - 0.0
  - 0.0
camera_pose:
  rotation_deg:
  - 180.0
  - 0.0
  - 0.0
  translation:
  - 0.6
  - 0.0
  - 0.5
alignment:
  icp_threshold: 0.05
  init_rotation_deg:
  - 0.0
  - 0.0
  - 0.0
  init_translation:
  - 0.0
  - 0.0
  - 0.0
  skip_ransac: true
  visualize: true
  voxel_size: 0.004
paths:
  intermediate_results: intermediate_results
  model_weights_path: ../notebooks/runs/segment/train11/weights/best.pt
model_mapping:
  Plate 1: object_models/Plate1.ply
  Plate 2: object_models/Plate2.ply
  Plate 3: object_models/Plate3.ply
  Plate 4: object_models/Plate4.ply
  Plate 5: object_models/Plate5.ply
segmentation:
  confidence_threshold: 0.6
valid_classes:
- Plate 1
- Plate 2
- Plate 3
- Plate 4
- Plate 5
