model_dir: object_models
render_overlay_default: true
output_units: deg
icp_threshold: 0.002
max_icp_iterations: 50
robot_pose:
  translation:
  - 0.0
  - 0.0
  - 0.0
  rotation_deg:
  - 0.0
  - 0.0
  - 0.0
camera_pose:
  rotation_deg:
  - 180.0
  - 0.0
  - 0.0
  translation:
  - 0.6
  - 0.0
  - 0.5
alignment:
  icp_threshold: 0.3
  init_rotation_deg:
  - 0.0
  - 0.0
  - 0.0
  init_translation:
  - 0.0
  - 0.0
  - 0.0
  skip_ransac: true
  visualize: true
  voxel_size: 0.0003
paths:
  intermediate_results: intermediate_results
  # model_weights_path: ../runs/segment/train8/weights/best.pt
  model_weights_path: ../notebooks/best.pt

model_mapping:
  Plate 1: object_models/Plate1.ply
  Plate 2: object_models/Plate2.ply
  Plate 3: object_models/Plate3.ply
  Plate 4: object_models/Plate4.ply
  Plate 5: object_models/Plate5.ply
segmentation:
  confidence_threshold: 0.6
valid_classes:
- Plate 1
- Plate 2
- Plate 3
- Plate 4
- Plate 5

camera:
  rgb:
    resolution: [1920, 1080]
    fps: 30
    auto_exposure: false
    gain: 64
    brightness: 0
    contrast: 50
    gamma: 150
    saturation: 15
    sharpness: 50
    auto_white_balance: 1

  depth:
    resolution: [1280, 720]
    fps: 30
    visual_preset: "high_accuracy"   # or "high_density"
    laser_power: 200
    confidence_threshold: 1

  alignment:
    align_depth_to_color: true

  post_processing:
    decimation:
      enabled: true
      magnitude: 2
    spatial:
      enabled: true
      magnitude: 3
      smooth_alpha: 0.45
      smooth_delta: 17
    temporal:
      enabled: true
      smooth_alpha: 0.39
      smooth_delta: 38